datadump.location:
    author: D:/Development/Spring Boot Projects/Novelist/Datasets/authors.txt
    works: D:/Development/Spring Boot Projects/Novelist/Datasets/works.txt

spring:
    data:
        cassandra:
            keyspace-name: main
            username: wRvypFuqcJTmzPzRPUckUsvr
            password: Owhk0iIfBoxuXslixwGzn8sF+a5hZ4_BlCuL4HzA5WyE0W00dA3D09x6hCBXUODCUZb3t_EhNXtyOkKxfmsZ0P1d46-MCiqgEi.H3gKYC6J-bWG-jSAYvqwGBZKMls63
            schema-action: CREATE_IF_NOT_EXISTS
            request:
                timeout: 10s
            connection:
                connect-timeout: 10s
                init-query-timeout: 10s
 
    main:
        allow-circular-references: true

datastax.astra:
    secure-connect-bundle: secure-connect.zip


astra.db:
    id: 98c7b0b4-09ef-4dba-b76a-2e720645c5c8-1
    region: asia-south1
    keyspace: main
    application.token: AstraCS:wRvypFuqcJTmzPzRPUckUsvr:6cdb7bb66ae9192b08b2ff6be748123b0a9974abe91104b2e3c0231d4079fe05
